import React from 'react'
import Helmet from 'react-helmet'
import Page from '../components/Page'

export default () => (
  <Page>
    <h1>This is the <strong>BAROT</strong> view.</h1>
    <p>RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROTRAHUL BAROTRAHUL BAROTRAHUL BAROT RAHUL BAROTRAHUL BAROTRAHUL BAROTRAHUL BAROTRAHUL BAROTrdum quisque duis mauris scelerisque scelerisque dui elit a condimentum vestibulum ad vestibulum. Laoreet nostra dui vivamus vestibulum integer taciti suscipit consectetur in a nullam quam nam ad nunc class nec ullamcorper urna sed nascetur ad. Vestibulum a sem leo nunc condimentum vestibulum euismod sapien aenean adipiscing a mi volutpat non fames. Adipiscing parturient parturient sit nec viverra tristique dui senectus commodo sem eu vestibulum vestibulum lorem ullamcorper. A quis a volutpat posuere suspendisse commodo nec elit parturient parturient sit ac sed suspendisse nam ullamcorper. Sit in a ut vivamus fringilla penatibus suspendisse scelerisque eu bibendum a egestas sodales vel rhoncus phasellus suspendisse faucibus viverra ultricies fusce laoreet libero a taciti.</p>
    <p>EHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROTRAHUL BAROTRAHUL nt consectetur a etiam class consectetur a in massa parturient hac sed litora massa. Arcu enim arcu ac interdum ullamcorper consectetur aptent natoque curae mattis adipiscing a non metus netus arcu accumsan nam quisque condimentum posuere platea congue nisl mollis id nascetur.</p>
    <p>FHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROTRAHUL BAROTRAHUL stibulum habitasse ac dignissim a interdum fringilla nisi tortor eget dictum netus curae a pulvinar semper feugiat pharetra. Cras facilisis feugiat mi urna nec porttitor id leo suspendisse suspendisse phasellus parturient lacus lobortis condimentum a mus. Mi nam phasellus ridiculus est nisl nullam maecenas eu a erat proin facilisis at massa sit ac aenean tempus sed pharetra curabitur gravida nulla dapibus in. Dolor venenatis sit ullamcorper suspendisse eu ac ridiculus a adipiscing et a suscipit lectus turpis volutpat lectus tincidunt per rutrum vestibulum consectetur consectetur adipiscing quam.</p>
    <p>UHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROTRAHUL BAROTRAHUL apibus vestibulum facilisi parturient ullamcorper vulputate a ullamcorper pulvinar justo platea fermentum aptent. Lectus condimentum vestibulum ut faucibus vulputate a feugiat aliquet faucibus platea iaculis sed condimentum vulputate scelerisque a eu in mi ullamcorper scelerisque adipiscing et fames parturient mollis adipiscing varius.</p>
    <p>DoHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROTRAHUL BAROTRAHUL estibulum fringilla mi pulvinar in erat aptent vestibulum nisi a enim vestibulum parturient. Laoreet ad in aliquet magna accumsan donec fringilla tellus consectetur vulputate dui interdum nisl sociis aliquam sociis adipiscing quisque adipiscing et velit.</p>
    <p>Sit vHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROT RAHUL BAROTRAHUL BAROTRAHUL s parturient phasellus ullamcorper eros hac malesuada aliquet suspendisse duis laoreet cum augue proin consectetur feugiat a scelerisque taciti ullamcorper parturient. Ut vel parturient parturient consectetur vel eros quisque tellus etiam parturient integer eleifend quisque condimentum faucibus congue nisi facilisi quam a pharetra viverra montes. Ad magna a curae turpis auctor condimentum nulla massa ligula himenaeos tempor a integer condimentum integer.</p>
    <Helmet title='Home' />
  </Page>
)
